#!/bin/sh

# a script to generate an "upstream tarball" from the main svn.

# Author: Daniel Kahn Gillmor <dkg@fifthhorseman.net>

# Usage: invoke this from the top level of the source, with:
#   make -f debian/rules get-orig-source

set -e
set -x

SVN_VERS=$(svn info http://svn.xiph.org/trunk/Tremor | grep '^Last Changed Rev:' | cut -f4 -d' ')

DIRNAME="libvorbisidec-1.0.2+svn${SVN_VERS}"
TARBALL="../libvorbisidec_1.0.2+svn${SVN_VERS}.orig.tar.gz"

if [ -e "$TARBALL" ] ; then
    printf '%s already exists.\n' "$TARBALL" >&2
    exit 1
fi

svn export -q http://svn.xiph.org/trunk/Tremor "debian/$DIRNAME"
tar c -C debian "$DIRNAME"  | gzip -9 -n > "$TARBALL"
rm -rf "debian/$DIRNAME"

ls -la "$TARBALL"

