#!/usr/bin/make

# makefile documenting how to build ivorbisfile_example.c from the
# libvorbisidec ("tremor") library distribution.

# Author: Daniel Kahn Gillmor <dkg@fifthhorseman.net>

ivorbisfile_example: ivorbisfile_example.c
	gcc -g -o ivorbisfile_example ivorbisfile_example.c -lvorbisidec
